name: update-readme_md_from_github_profile
on:
  workflow_dispatch:
  push:
    branches:
      - about-me
permissions: write-all
jobs:
  download_from_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download
        run: |
          curl https://raw.githubusercontent.com/thedaveCA/thedaveCA/main/README.md -o .github/README.download
          touch .github/README.md
      - name: Prepare
        run: |
          printf -- "---\nlayout: default\npermalink: /about:me/\nredirect_from:\n  - /about\n  - /about/\n  - /about:me\n---\n" | cat - .github/README.download > docs/ABOUTME.md
      - name: git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          diff .github/README.download .github/README.md && exit 0
          mv .github/README.download .github/README.md
          git add .
          git commit -m "Automatic - Update /thedave.dev/README.md"
          git push
